import { ReactNode } from 'react'
import Head from 'next/head'

const GuestLayout: React.FC<{ children: ReactNode }> = ({ children }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>
                {children}
            </div>
        </div>
    )
}

export default GuestLayout
