import Head from "next/head";
import React from "react";
import { useDispatch } from "react-redux";

import AppLayout from "components/Layouts/AppLayout";
import { useShowForPost } from "hooks/posts/swr/useShowForPost";
import { useAuth } from "hooks/useAuth";
import { setUserId } from "store/modules/postSearch";

import type { NextPage } from "next";

const Post: NextPage = () => {
  const dispatch = useDispatch();

  const { logout } = useAuth();
  const post = useShowForPost();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <button type="button" onClick={logout}>
          Logout
        </button>

        {post && (
          <div>
            <div>{post.text}</div>
            <div onClick={() => dispatch(setUserId(post.user_id))}>
              {post.created_by}
            </div>
          </div>
        )}
      </AppLayout>
    </>
  );
};

export default Post;
