import AppLayout from 'components/Layouts/AppLayout'
import Head from 'next/head'
import { useAuth } from 'hooks/auth'

const Dashboard = () => {
    const { logout } = useAuth()

    return (
        <AppLayout
            header={
                <h2>Dashboard</h2>
            }>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div>You&apos;re logged in!</div>
            <button type="button" onClick={logout}>Logout</button>
        </AppLayout>
    )
}

export default Dashboard
