import Head from "next/head";
import { useEffect, useState } from "react";

import AppLayout from "components/Layouts/AppLayout";
import GuestLayout from "components/Layouts/GuestLayout";
import { useAuth } from "hooks/useAuth";
import { usePosts } from "hooks/usePosts";

import type { NextPage } from "next";
import type { Posts } from "types/posts";

const Home: NextPage = () => {
  const { user, logout } = useAuth();
  const { getPosts } = usePosts();
  const [posts, setPosts] = useState<Posts>(null);

  useEffect(() => {
    getPosts({ setPosts, page: 1, order_by: "created_at", order: "desc" });
  }, []);

  return (
    <div>
      {user ? (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <AppLayout>
            <button type="button" onClick={logout}>
              Logout
            </button>

            {posts?.data.map((post) => {
              return (
                <div key={post.id}>
                  <hr />
                  <div>{post.text}</div>
                  <div>{post.created_by}</div>
                </div>
              );
            })}
          </AppLayout>
        </>
      ) : (
        <GuestLayout>
          <h2>ホーム</h2>
        </GuestLayout>
      )}
    </div>
  );
};

export default Home;
