import Head from "next/head";

import AppLayout from "components/Layouts/AppLayout";
import GuestLayout from "components/Layouts/GuestLayout";
import { useAuth } from "hooks/useAuth";

import type { NextPage } from "next";

const Home: NextPage = () => {
  const { user, logout } = useAuth();

  return (
    <div>
      {user ? (
        <>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <AppLayout>
            <button type="button" onClick={logout}>
              Logout
            </button>
          </AppLayout>
        </>
      ) : (
        <GuestLayout>
          <h2>ホーム</h2>
        </GuestLayout>
      )}
    </div>
  );
};

export default Home;
