import Head from "next/head";
import Link from "next/link";

import AppLayout from "components/Layouts/AppLayout";
import GuestLayout from "components/Layouts/GuestLayout";
import { useAuth } from "hooks/auth";

import type { NextPage } from "next";

const Home: NextPage = () => {
  const { user, logout } = useAuth({ middleware: "guest" });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {user ? (
        <AppLayout header={<h2>Home</h2>}>
          <div>You&apos;re logged in!</div>
          <button type="button" onClick={logout}>
            Logout
          </button>
        </AppLayout>
      ) : (
        <GuestLayout>
          <Link href="/login">
            <a>Login</a>
          </Link>

          <Link href="/register">
            <a>Register</a>
          </Link>
        </GuestLayout>
      )}
    </div>
  );
};

export default Home;
